# GitHub Copilot Review Ruleset for Syncfusion .NET MAUI Toolkit
# This ruleset provides guidelines for automated code reviews for the maui-toolkit repository

name: "Syncfusion MAUI Toolkit Code Review Rules"
description: "Automated code review rules for the Syncfusion .NET MAUI Toolkit repository"

# Apply to all pull requests targeting the main branch
on:
  pull_request:
    branches: [main]
    paths:
      - 'maui/src/**'
      - 'maui/tests/**'
      - 'maui/samples/**'
      - '*.cs'
      - '*.csproj'
      - '*.xaml'
      - '*.xml'

rules:
  # .NET and C# Best Practices
  - name: "Ensure async methods follow naming conventions"
    description: "Async methods should end with 'Async' suffix"
    pattern: "public.*async.*Task.*(?!.*Async)"
    severity: "warning"
    message: "Async methods should end with 'Async' suffix for better code readability"

  - name: "Check for proper disposal of IDisposable objects"
    description: "Ensure IDisposable objects are properly disposed"
    pattern: "new.*\\(.*\\)(?!.*using|.*Dispose)"
    severity: "warning"
    message: "Consider using 'using' statement or ensure proper disposal of IDisposable objects"

  - name: "Validate null checking patterns"
    description: "Use modern null checking patterns"
    pattern: "if.*==\\s*null|if.*!=\\s*null"
    severity: "info"
    message: "Consider using null-conditional operators (?.) or is null/is not null patterns"

  # MAUI-Specific Rules
  - name: "Check XAML binding syntax"
    description: "Ensure proper XAML binding syntax"
    pattern: "Binding\\s+[^\\}]*(?!Path=|Source=)"
    severity: "warning"
    message: "XAML bindings should specify Path or Source for clarity"

  - name: "Platform-specific code organization"
    description: "Ensure platform-specific code is properly organized"
    pattern: "#if.*ANDROID|#if.*IOS|#if.*WINDOWS"
    severity: "info" 
    message: "Consider using platform-specific implementations in separate files or handlers where possible"

  - name: "Dependency injection registration"
    description: "Check for proper DI registration patterns"
    pattern: "services\\.Add.*\\(.*new.*\\)"
    severity: "warning"
    message: "Avoid creating instances in DI registration. Use factory methods or proper lifetime management"

  # Syncfusion Toolkit Specific Rules
  - name: "Control base class inheritance"
    description: "Ensure custom controls inherit from appropriate base classes"
    pattern: "class.*:.*Control|class.*:.*View"
    severity: "info"
    message: "Verify that custom controls inherit from appropriate MAUI base classes"

  - name: "Bindable property declarations"
    description: "Check for proper bindable property patterns"
    pattern: "BindableProperty\\.Create"
    severity: "info"
    message: "Ensure bindable properties follow MAUI conventions with proper default values and property changed callbacks"

  - name: "Resource dictionary organization"
    description: "Check for proper resource organization"
    pattern: "<ResourceDictionary"
    severity: "info"
    message: "Ensure resources are properly organized and themed consistently across the toolkit"

  # Performance and Memory Management
  - name: "Event handler memory leaks"
    description: "Check for potential memory leaks with event handlers"
    pattern: "\\+=.*new.*\\(|\\+=.*=>"
    severity: "warning"
    message: "Be cautious of memory leaks. Consider weak event patterns or proper cleanup in Dispose methods"

  - name: "Collection initialization"
    description: "Use efficient collection initialization"
    pattern: "new List<.*>\\(\\).*Add\\("
    severity: "info"
    message: "Consider using collection initializers or capacity hints for better performance"

  # API Design and Documentation
  - name: "Public API documentation"
    description: "Ensure public APIs are properly documented"
    pattern: "public.*(?!.*///)(?!.*<summary>)"
    severity: "warning" 
    message: "Public APIs should include XML documentation comments"

  - name: "Obsolete attribute usage"
    description: "Check for proper obsolete attribute usage"
    pattern: "\\[Obsolete\\]"
    severity: "info"
    message: "Ensure obsolete members include migration guidance and version information"

  # Testing Requirements
  - name: "Unit test coverage"
    description: "Encourage unit test coverage for new functionality"
    pattern: "public.*class.*(?!.*Test)"
    severity: "info"
    message: "Consider adding unit tests for new public classes and methods"

  - name: "Test method naming"
    description: "Ensure test methods follow naming conventions"
    pattern: "\\[Test\\].*public.*(?!.*Should.*When)"
    severity: "info"
    message: "Consider using descriptive test names that describe the expected behavior"

  # Security and Validation
  - name: "Input validation"
    description: "Check for proper input validation"
    pattern: "public.*\\(.*string.*\\)(?!.*ArgumentNullException|.*ArgumentException)"
    severity: "warning"
    message: "Public methods accepting string parameters should validate input"

  - name: "Configuration validation"
    description: "Validate configuration and settings"
    pattern: "Configuration\\.|Settings\\."
    severity: "info"
    message: "Ensure configuration values are validated before use"

  # File and Project Structure
  - name: "File naming conventions"
    description: "Ensure files follow proper naming conventions"
    pattern: "^[a-z].*\\.cs$"
    severity: "warning"
    message: "C# files should use PascalCase naming convention"

  - name: "Namespace organization"
    description: "Check namespace organization"
    pattern: "namespace.*(?!Syncfusion\\.Maui\\.Toolkit)"
    severity: "warning"
    message: "Ensure namespaces follow the project structure: Syncfusion.Maui.Toolkit.*"

# Exclusions
exclude:
  paths:
    - 'maui/samples/*/bin/**'
    - 'maui/samples/*/obj/**'
    - 'maui/src/obj/**'
    - 'maui/tests/*/bin/**'
    - 'maui/tests/*/obj/**'
    - '**/*.Designer.cs'
    - '**/AssemblyInfo.cs'
  
# Review behavior
review:
  auto_approve: false  # Require human review
  require_review_from_codeowners: true
  dismiss_stale_reviews: true
  
# Integration settings
integrations:
  copilot:
    enabled: true
    review_level: "detailed"  # Options: basic, detailed, comprehensive
    focus_areas:
      - "performance"
      - "security" 
      - "maintainability"
      - "maui_best_practices"
      - "api_design"