# GitHub Copilot Review Configuration
# This file configures automated code review using GitHub Copilot for the Syncfusion .NET MAUI Toolkit

# General Configuration
extends: []  # No parent rulesets to extend

# Repository Information
repository:
  name: "maui-toolkit"
  description: "Syncfusion Toolkit for .NET MAUI"
  primary_language: "C#"
  frameworks: ["MAUI", "NET8", "NET9"]

# Review Scope
scope:
  include_paths:
    - "maui/src/**"
    - "maui/tests/**"
    - "maui/samples/**"
  exclude_paths:
    - "**/bin/**"
    - "**/obj/**"
    - "**/*.Designer.cs"
    - "**/AssemblyInfo.cs"
    - "**/GlobalUsings.cs"

# Code Review Rules
rules:
  # Performance Rules
  performance:
    - id: "perf-001"
      name: "Async Method Efficiency"
      description: "Review async methods for proper patterns and performance"
      severity: "warning"
      enabled: true
      
    - id: "perf-002" 
      name: "UI Thread Operations"
      description: "Ensure UI operations are performed on the main thread"
      severity: "error"
      enabled: true
      
    - id: "perf-003"
      name: "Memory Management"
      description: "Check for potential memory leaks and proper disposal"
      severity: "warning"
      enabled: true

  # MAUI Framework Rules
  maui:
    - id: "maui-001"
      name: "Bindable Properties"
      description: "Validate bindable property implementations"
      severity: "warning"
      enabled: true
      
    - id: "maui-002"
      name: "Platform Handlers"
      description: "Review platform-specific handler implementations"
      severity: "info"
      enabled: true
      
    - id: "maui-003"
      name: "Cross-Platform Compatibility"
      description: "Ensure code works across all MAUI platforms"
      severity: "error"
      enabled: true

  # API Design Rules  
  api_design:
    - id: "api-001"
      name: "Public API Documentation"
      description: "Ensure all public APIs have XML documentation"
      severity: "warning"
      enabled: true
      
    - id: "api-002"
      name: "Naming Conventions"
      description: "Validate .NET naming conventions"
      severity: "warning"
      enabled: true
      
    - id: "api-003"
      name: "Backwards Compatibility"
      description: "Check for breaking changes in public APIs"
      severity: "error"
      enabled: true

  # Security Rules
  security:
    - id: "sec-001"
      name: "Input Validation"
      description: "Ensure proper validation of user inputs"
      severity: "warning"
      enabled: true
      
    - id: "sec-002"
      name: "Resource Access"
      description: "Review file and network access patterns"
      severity: "info"
      enabled: true

  # Testing Rules
  testing:
    - id: "test-001"
      name: "Unit Test Coverage"
      description: "Encourage unit tests for new functionality"
      severity: "info"
      enabled: true
      
    - id: "test-002"
      name: "Test Naming"
      description: "Validate test method naming conventions"
      severity: "info"
      enabled: true

# Custom Review Prompts
review_prompts:
  - name: "MAUI Control Review"
    trigger: "files:maui/src/**/*.cs"
    prompt: |
      When reviewing MAUI control implementations, please focus on:
      1. Proper inheritance from MAUI base classes
      2. Correct bindable property patterns
      3. Platform handler implementations
      4. Performance in measure/arrange cycles
      5. Memory management and disposal
      6. Accessibility features
      7. Cross-platform compatibility

  - name: "Chart Performance Review"
    trigger: "files:maui/src/Charts/**/*.cs"
    prompt: |
      For chart-related code, pay special attention to:
      1. Rendering performance with large datasets
      2. Memory usage during data updates
      3. Smooth animations and transitions
      4. Touch interaction responsiveness
      5. Data binding efficiency

  - name: "Test Quality Review" 
    trigger: "files:maui/tests/**/*.cs"
    prompt: |
      When reviewing test code, ensure:
      1. Tests are isolated and deterministic
      2. Proper use of mocking frameworks
      3. Coverage of edge cases and error conditions
      4. Clear test naming and organization
      5. Async test patterns are correct

# Review Behavior
behavior:
  auto_request_reviews: true
  review_draft_prs: false
  review_dependabot_prs: false
  
# Reviewer Assignment
reviewers:
  code_owners: true
  teams: []
  individuals: []

# Integration Settings
integrations:
  github_advanced_security: true
  dependency_review: true
  
# Notification Settings
notifications:
  review_requested: true
  review_completed: true
  high_severity_issues: true